"""
Django settings for BillingSystem project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vdw%1ac40k4azrfa!i#t-=s*+(2h5=gnrrs#0o)w!65tf1wq6a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'BillingSystem.billing.apps.BillingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BillingSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'BillingSystem.wsgi.application'


# Database
# Reload trigger - templatetags recreated
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#Local Database Configuration

# SQLite Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#To activate postgresql database and AWS RDS database 
# update the required fields

# PostgreSQL Database

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "[DB_NAME]",
#         "USER": "postgres",
#         "PASSWORD": "[PASSWORD]",
#         "HOST": "127.0.0.1",
#         "PORT": "5432",
#     }
# }

#AWS RDS Configuration
# check connectivity through powershell:
# Test-NetConnection database-1.cfwwmwcaoi6l.ap-south-1.rds.amazonaws.com -Port 5432

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "[DB_NAME]",
#         "USER": "postgres",
#         "PASSWORD": "[PASSWORD]",
#         "HOST": "[IP_ADDRESS]",
#         "PORT": "5432",
#     }
# }

# AWS S3 Configuration

# AWS_ACCESS_KEY_ID = '[ENCRYPTION_KEY]'
# AWS_SECRET_ACCESS_KEY = '[ACCESS_KEY]'
# AWS_STORAGE_BUCKET_NAME = '[BUCKET_NAME]'
# AWS_S3_SIGNATURE_NAME = 's3v4',
# AWS_S3_REGION_NAME = '[REGION_NAME]'
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL =  None
# AWS_S3_VERITY = True
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage' 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
# Time zone settings
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth Settings
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Razorpay Settings
RAZORPAY_KEY_ID = ''  # Replace with your Razorpay Key ID
RAZORPAY_KEY_SECRET = ''  # Replace with your Razorpay Key Secret

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# Force reload for template detection
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration Quick Setup Script
# Save this file and follow the instructions below

# STEP 1: Get your Gmail App Password
# -------------------------------------
# 1. Open: https://myaccount.google.com/apppasswords
# 2. Enable 2-Factor Authentication if you haven't
# 3. Generate an app password for "Mail"
# 4. Copy the 16-character password

# STEP 2: Run these commands in PowerShell
# -----------------------------------------
# Replace the placeholders below with your actual email and app password

# Example:
# setx EMAIL_HOST_USER "myemail@gmail.com"
# setx EMAIL_HOST_PASSWORD "abcd efgh ijkl mnop"

# Run these in PowerShell (replace with YOUR values):
# setx EMAIL_HOST_USER "[EMAIL_ADDRESS]"
# setx EMAIL_HOST_PASSWORD "xxxx xxxx xxxx xxxx"

# STEP 3: Restart Everything
# ---------------------------
# 1. Close this PowerShell window
# 2. Open a NEW PowerShell window
# 3. Navigate to your project
# 4. Run: python manage.py runserver

# STEP 4: Verify
# --------------
# Check if variables are set:
# echo %EMAIL_HOST_USER%
# echo %EMAIL_HOST_PASSWORD%

# Email Configuration - Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = f'Chargebee Billing System <{EMAIL_HOST_USER}>'

# For development/testing, uncomment the line below to print emails to console instead
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
