# Generated by Django 5.2.10 on 2026-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='footer_text',
            field=models.TextField(blank=True, default='', help_text='Text to display at the bottom of invoices'),
        ),
        migrations.AddField(
            model_name='company',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='swift_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax ID / GSTIN', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
