# Generated by Django 5.1.5 on 2026-02-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name cached for deleted products', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='billing.product'),
        ),
    ]
