# Generated by Django 5.1.5 on 2026-02-12 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_company_city_company_company_type_company_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
