# Generated by Django 5.1.5 on 2026-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_details',
            field=models.TextField(blank=True, default='', help_text='Override bank details for this invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_through',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.TextField(blank=True, default='', help_text='e.g. Net 30, Payment Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
