# Generated by Django 5.1.5 on 2026-02-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_bank_details_invoice_dispatch_through_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', help_text='Default Terms & Conditions for new invoices'),
        ),
    ]
