# Generated by Django 5.1.5 on 2026-02-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_company_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.product'),
        ),
    ]
