# Generated by Django 5.1.5 on 2026-02-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_remove_invoiceitem_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='Last time this invoice was emailed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emailed_to',
            field=models.EmailField(blank=True, default='', help_text='Email address the invoice was sent to', max_length=254),
        ),
    ]
