# Generated by Django 5.1.5 on 2026-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoicefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Indicates if a payment reminder has been sent by the admin'),
        ),
    ]
