# Generated by Django 5.1.5 on 2026-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_invoice_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
